server.port=8081
user-service.url=8085
user-service.internal-secret: YOUR_INTERNAL_SHARED_SECRET

spring.datasource.url=jdbc:mysql://localhost:3306/foodie_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=auth-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
# Expose the Prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=prometheus,health

# Add an 'application' tag to all metrics for this service
management.metrics.tags.application=${spring.application.name}
