server.port=8087

spring.application.name=notification-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Expose the Prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=prometheus,health

# Add an 'application' tag to all metrics for this service
management.metrics.tags.application=${spring.application.name}