server.port=8761

spring.application.name=discovery-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Expose the Prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=prometheus,health

# Add an 'application' tag to all metrics for this service
management.metrics.tags.application=${spring.application.name}