server.port=8084

spring.application.name=restaurant-service

spring.data.mongodb.uri=mongodb://localhost:27017/foodie_restaurant
spring.data.mongodb.auto-index-creation=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
# in application.properties
spring.elasticsearch.uris=http://localhost:9200
# Expose the Prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=prometheus,health

# Add an 'application' tag to all metrics for this service
management.metrics.tags.application=${spring.application.name}