server.port=8086

spring.application.name=delivery-service

spring.data.mongodb.uri=mongodb://localhost:27017/foodie_delivery

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Feign: call order-service on localhost (adjust if gateway used)
order.service.base-url=http://localhost:8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
# Expose the Prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=prometheus,health

# Add an 'application' tag to all metrics for this service
management.metrics.tags.application=${spring.application.name}